import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../../themes";

export const styles=StyleSheet.create({
    container:{
        flex:1,
    },
    emptyCartContainer:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
    },
    emptyCartText:{
        fontFamily:FONTS.regular,
        fontSize:16,
    },
    listContainer:{
        flex:1,
        backgroundColor:COLORS.wihte,
    },
    footerContainer:{
        backgroundColor:COLORS.background,
        borderTopColor:COLORS.secondary,
        borderTopWidth:4,
        padding:10,
    },
    checkoutButtonText:{
        color:COLORS.wihte,
        fontFamily:FONTS.bold,
    },
    totalContainer:{
        flexDirection:'row',
        gap:5,
    },
    totalText:{
        color:COLORS.wihte,
        fontFamily:FONTS.bold,
    },
    totalPrice:{
        color:COLORS.wihte,
        fontFamily:FONTS.bold,
    },
    checkOutButton:{
        backgroundColor:COLORS.secondary,
        borderRadius:5,
        paddingHorizontal:20,
        paddingVertical:10,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        height:50,
    },
})